name: Deploy to Vercel

on:
  workflow_dispatch:  # Permite ejecutar manualmente desde la interfaz de GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Debug secrets availability
        run: |
          echo "VERCEL_TOKEN est치 configurado: ${{ secrets.VERCEL_TOKEN != '' }}"
          echo "VERCEL_ORG_ID est치 configurado: ${{ secrets.VERCEL_ORG_ID != '' }}"
          echo "VERCEL_PROJECT_ID est치 configurado: ${{ secrets.VERCEL_PROJECT_ID != '' }}"
      
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          # Instalar Vercel CLI
          npm install -g vercel
          
          # Crear archivo de configuraci칩n
          mkdir -p .vercel
          echo "{\"orgId\":\"$VERCEL_ORG_ID\",\"projectId\":\"$VERCEL_PROJECT_ID\"}" > .vercel/project.json
          
          # Desplegar a Vercel
          vercel --prod --token=$VERCEL_TOKEN --yes
